openapi: 3.0.0
info:
  title: DTP Map API
  description: API для получения данных по ДТП, объектам и словарям
  version: 1.0.3

paths:
  # =========================
  # Маршруты для ДТП
  # =========================
  /dtp/api/dtp/coord:
    get:
      summary: Получение данных о ДТП с фильтрацией
      description: Возвращает данные ДТП с фильтрацией по году, МО и виду ДТП.
      parameters:
        - name: year
          in: query
          required: false
          description: Год ДТП
          schema:
            type: integer
            example: 2024
        - name: mo
          in: query
          required: false
          description: ID муниципального образования
          schema:
            type: integer
            example: 1
        - name: vid_dtp
          in: query
          required: false
          description: ID вида ДТП
          schema:
            type: integer
            example: 2
      responses:
        "200":
          description: Успешный ответ с данными ДТП
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_kard:
                      type: integer
                      example: 12345
                    year:
                      type: integer
                      example: 2024
                    mo:
                      type: integer
                      example: 1
                    vid_dtp:
                      type: integer
                      example: 3
                    coord_w:
                      type: number
                      example: 55.7558
                    coord_l:
                      type: number
                      example: 37.6173

  /dtp/api/dtp/card/{id_kard}:
    get:
      summary: Получение карточки ДТП
      description: Возвращает карточку ДТП по id_kard
      parameters:
        - name: id_kard
          in: path
          required: true
          description: ID карточки ДТП
          schema:
            type: integer
            example: 222033880
      responses:
        "200":
          description: Успешный ответ с карточкой ДТП
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_kard:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Номер ДТП"
                      value:
                        type: integer
                        example: 221973828
                  address:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Адрес"
                      value:
                        type: string
                        example: "ул. Ленина, 25"
                  date_dtp:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Дата ДТП"
                      value:
                        type: string
                        example: "12.03.2024"
                  vid_dtp:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Вид ДТП"
                      value:
                        type: string
                        example: "Столкновение"
                  ndu:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Проблемы УДС (перегон)"
                      value:
                        type: string
                        example: "Отсутствие разметки"
                  mo:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Муниципальный округ"
                      value:
                        type: string
                        example: "Кемеровский городской округ"
                  sost_pogodi:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Погода"
                      value:
                        type: string
                        example: "Пасмурно"
                  sost_proez_chasti:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Состояние проезжей части"
                      value:
                        type: string
                        example: "Обработано противогололедными материалами"
                  osveshenie:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Освещение"
                      value:
                        type: string
                        example: "В темное время суток, освещение включено"
                  vina:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Нарушения"
                      value:
                        type: array
                        items:
                          type: object
                          properties:
                            uch:
                              type: object
                              properties:
                                title:
                                  type: string
                                  example: "Участник ДТП"
                                value:
                                  type: object
                                  properties:
                                    type:
                                      type: object
                                      properties:
                                        title:
                                          type: string
                                          example: "Участник"
                                        value:
                                          type: string
                                          example: "Водитель"
                                    ts:
                                      type: object
                                      properties:
                                        title:
                                          type: string
                                          example: "Транспортное средство"
                                        value:
                                          type: string
                                          example: "1"
                                    narushenie:
                                      type: object
                                      properties:
                                        title:
                                          type: string
                                          example: "Нарушения"
                                        value:
                                          type: array
                                          items:
                                            type: string
                                            example: "Выезд на полосу встречного движения"
                                    stepen_tyazhesti:
                                      type: object
                                      properties:
                                        title:
                                          type: string
                                          example: "Степень тяжести"
                                        value:
                                          type: string
                                          example: "Ранен"
                  pogibshie:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Погибшие"
                      value:
                        type: integer
                        example: 2
                  ranenie:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Раненые"
                      value:
                        type: integer
                        example: 3


  # =========================
  # Маршруты для объектов
  # =========================
  /dtp/api/objects/traffic_cameras:
    get:
      summary: Данные по камерам
      description: Возвращает данные по камерам в формате JSON.
      responses:
        "200":
          description: Успешный ответ с данными о камерах
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    coord_w:
                      type: number
                      example: 55.7558
                    coord_l:
                      type: number
                      example: 37.6173
                    type_data:
                      type: integer
                      example: 2
                    metka_mo:
                      type: integer
                      example: 2

  /dtp/api/objects/uchrez:
    get:
      summary: Данные по учреждениям
      description: Возвращает данные об учреждениях в формате JSON.
      responses:
        "200":
          description: Успешный ответ с данными об учреждениях
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type_uchrez:
                      type: integer
                      example: 2
                    coord_w:
                      type: number
                      example: 55.7558
                    coord_l:
                      type: number
                      example: 37.6173
                    type_data:
                      type: integer
                      example: 2

  # =========================
  # Маршруты для словарей
  # =========================
  /dtp/api/dict/mo:
    get:
      summary: Словарь МО
      description: Возвращает данные по муниципальным образованиям.
      responses:
        "200":
          description: Успешный ответ с данными МО
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    mo:
                      type: string
                      example: "Москва"

  /dtp/api/dict/narusheniya:
    get:
      summary: Словарь нарушений
      description: Возвращает данные по нарушениям.
      responses:
        "200":
          description: Успешный ответ с данными нарушений
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    narushenie:
                      type: string
                      example: "Проезд на красный свет"

  /dtp/api/dict/osveshenie:
    get:
      summary: Словарь освещения
      description: Возвращает данные по условиям освещения.
      responses:
        "200":
          description: Успешный ответ с данными освещения
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    osveshenie:
                      type: string
                      example: "Темное время суток"

  /dtp/api/dict/sost_pogodi:
    get:
      summary: Словарь погодных условий
      description: Возвращает данные по состоянию погоды.
      responses:
        "200":
          description: Успешный ответ с данными погодных условий
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    sost_pogodi:
                      type: string
                      example: "Дождь"

  /dtp/api/dict/sost_proez_chasti:
    get:
      summary: Словарь состояния проезжей части
      description: Возвращает данные по состоянию проезжей части.
      responses:
        "200":
          description: Успешный ответ с данными проезжей части
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    sost_proez_chasti:
                      type: string
                      example: "Гололед"

  /dtp/api/dict/vid_dtp:
    get:
      summary: Словарь видов ДТП
      description: Возвращает данные по видам ДТП.
      responses:
        "200":
          description: Успешный ответ с данными видов ДТП
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 3
                    vid_dtp:
                      type: string
                      example: "Столкновение"

  /dtp/api/dict/uchrez_type:
    get:
      summary: Словарь видов учреждений
      description: Возвращает данные по видам учреждений.
      responses:
        "200":
          description: Успешный ответ с данными видов учреждений
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Детский сад"

  /dtp/api/dict/vid_ndu:
    get:
      summary: Словарь видов "Недостатки транспортно эксплуатационного содержания улично дорожной сети"
      description: Возвращает данные по видам "Недостатки транспортно эксплуатационного содержания улично дорожной сети".
      responses:
        "200":
          description: Успешный ответ с данными видов "Недостатки транспортно эксплуатационного содержания улично дорожной сети"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    vid_dtp:
                      type: string
                      example: "Отсутствие тротуаров (пешеходных дорожек)"